### ISSUE TITLE
D-pad resets location

### ISSUE THREAD

**Issue by Djowietje** [jinsen47/PokeFaker#1]
When i open the app it places me in the middle of the ocean. I manually set it to a location in my neighbourhood (which works) but then when i press a key on the D-Pad i get ported back to that original location in the ocean.

**Comment by jinsen47** [comment]
Initial position is(0,0), which is in the middle of the atlantic. But when you select a position on the map, it will save the location, and next movement is based on the recent saved result. Did you granted all permission it declared?

**Comment by Djowietje** [comment]
Yeah Sorry it was my bad. I forgot to set Location Precision to GPS only so
i think that may have been the cause. Working fine now :) thanks m8

Op ma 18 jul. 2016 12:25 schreef Jinsen Sheng notifications@github.com:
