### ISSUE TITLE
Map shows just blue screen, pokemon go map turns black

### ISSUE THREAD

**Issue by sadone** [jinsen47/PokeFaker#13]
I have no idea what I could be doing wrong, but whenever I open PokeFaker the map where you're supposed to pick a location is just blue, i tried scrolling but nothing shows. If I open Pokemon Go after that, I can move around but everything around is just black. 
![screen shot 2016-07-22 at 08 38 07](https://cloud.githubusercontent.com/assets/20591439/17048669/f238eebc-4fe7-11e6-80eb-5ef77735d7ed.png)
![screen shot 2016-07-22 at 08 38 48](https://cloud.githubusercontent.com/assets/20591439/17048671/f47cb10e-4fe7-11e6-9d9b-5252017348d9.png)

**Comment by jinsen47** [comment]
Hi there,
You can update the 1.0.1 version, I have fixed the first problem.
For the second one, I was wondering something wrong about your hardware accelerating, maybe you are using a x86 tablet?

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com
