### ISSUE TITLE
Work but reboot my phone

### ISSUE THREAD

**Issue by Traupicaw** [jinsen47/PokeFaker#14]
Hi ! 
First I wanna thank you for this module. It works almost perfectly on my phone (Wiko Rainbow) but like every 5min +- my phone reboots... Any ideas why?

**Comment by jinsen47** [comment]
I guess your phone system detected a severe short for memory, and cannot do anything to trim some, so it reboots.
Does this happen without PokeFaker?

**Comment by Traupicaw** [comment]
Nope only happens when I use Pokefaker. I guess you might be right about memory; don't really know

**Comment by paddyponchero** [comment]
I have the reboot too, I have found if I tap the joystick to move it will keep working all day, i can even tap as fast as my fingers will go with no problem, however if i hold the joystick for a second or more the character will stop moving and after about 3-4 seconds the phone will reboot.

**Comment by paddyponchero** [comment]
Managed to logcat the error, don't know much about java is it possible to stick in a catch all?

07-27 03:23:53.276 W/System.err( 6396):     at android.os.Bundle.<init>(Bundle.java:119)
07-27 03:23:53.276 W/System.err( 6396):     at android.location.Location.set(Location.java:143)
07-27 03:23:53.276 W/System.err( 6396):     at android.location.Location.<init>(Location.java:123)
07-27 03:23:53.276 W/System.err( 6396):     at com.android.server.LocationManagerService.handleLocationChanged(LocationManagerService.java:2428)
07-27 03:23:53.276 W/System.err( 6396):     at com.android.server.LocationManagerService.access$1800(LocationManagerService.java:101)
07-27 03:23:53.276 W/System.err( 6396):     at com.android.server.LocationManagerService$LocationWorkerHandler.handleMessage(LocationManagerService.java:2413)
07-27 03:23:53.276 W/System.err( 6396):     at android.os.Handler.dispatchMessage(Handler.java:110)
07-27 03:23:53.276 W/System.err( 6396):     at android.os.Looper.loop(Looper.java:193)
07-27 03:23:53.276 W/System.err( 6396):     at android.os.HandlerThread.run(HandlerThread.java:61)
07-27 03:23:53.276 W/dalvikvm( 6396): threadid=18: calling UncaughtExceptionHandler

**Comment by paddyponchero** [comment]
07-27 03:24:03.876 E/LocationManager(12703): RemoteException
07-27 03:24:03.876 E/LocationManager(12703): android.os.DeadObjectException
07-27 03:24:03.876 E/LocationManager(12703):    at android.os.BinderProxy.transact(Native Method)
07-27 03:24:03.876 E/LocationManager(12703):    at android.location.ILocationManager$Stub$Proxy.setTestProviderLocation(ILocationManager.java:980)
07-27 03:24:03.876 E/LocationManager(12703):    at android.location.LocationManager.setTestProviderLocation(LocationManager.java:1260)
07-27 03:24:03.876 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider.postLocation(MockProvider.java:90)
07-27 03:24:03.876 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider.postLocation(MockProvider.java:86)
07-27 03:24:03.876 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider$1.onChanged(MockProvider.java:30)
07-27 03:24:03.876 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder.notifyDataObserver(LocationHolder.java:90)
07-27 03:24:03.876 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder.access$000(LocationHolder.java:22)
07-27 03:24:03.876 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder$1.run(LocationHolder.java:53)
07-27 03:24:03.876 E/LocationManager(12703):    at android.os.Handler.handleCallback(Handler.java:808)
07-27 03:24:03.876 E/LocationManager(12703):    at android.os.Handler.dispatchMessage(Handler.java:103)
07-27 03:24:03.876 E/LocationManager(12703):    at android.os.Looper.loop(Looper.java:193)
07-27 03:24:03.876 E/LocationManager(12703):    at android.app.ActivityThread.main(ActivityThread.java:5292)
07-27 03:24:03.876 E/LocationManager(12703):    at java.lang.reflect.Method.invokeNative(Native Method)
07-27 03:24:03.876 E/LocationManager(12703):    at java.lang.reflect.Method.invoke(Method.java:515)
07-27 03:24:03.876 E/LocationManager(12703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
07-27 03:24:03.876 E/LocationManager(12703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
07-27 03:24:03.876 E/LocationManager(12703):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-27 03:24:03.876 E/LocationManager(12703):    at dalvik.system.NativeStart.main(Native Method)
**07-27 03:24:03.877 E/AndroidRuntime(12703): FATAL EXCEPTION: RockerViewSurface**
07-27 03:24:03.877 E/AndroidRuntime(12703): Process: com.github.jinsen47.pokefaker, PID: 12703
07-27 03:24:03.877 E/AndroidRuntime(12703): java.lang.IllegalArgumentException
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.view.Surface.nativeUnlockCanvasAndPost(Native Method)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.view.Surface.unlockCanvasAndPost(Surface.java:270)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.view.SurfaceView$4.unlockCanvasAndPost(SurfaceView.java:978)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at com.gcssloop.widget.RockerView.run(RockerView.java:359)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.os.Handler.handleCallback(Handler.java:808)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.os.Handler.dispatchMessage(Handler.java:103)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.os.Looper.loop(Looper.java:193)
07-27 03:24:03.877 E/AndroidRuntime(12703):     at android.os.HandlerThread.run(HandlerThread.java:61)
07-27 03:24:03.880 E/SurfaceHolder(12703): Exception locking surface
07-27 03:24:03.880 E/SurfaceHolder(12703): java.lang.IllegalArgumentException
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.view.Surface.nativeLockCanvas(Native Method)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.view.Surface.lockCanvas(Surface.java:243)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.view.SurfaceView$4.internalLockCanvas(SurfaceView.java:940)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.view.SurfaceView$4.lockCanvas(SurfaceView.java:908)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at com.gcssloop.widget.RockerView.run(RockerView.java:344)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.os.Handler.handleCallback(Handler.java:808)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.os.Handler.dispatchMessage(Handler.java:103)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.os.Looper.loop(Looper.java:193)
07-27 03:24:03.880 E/SurfaceHolder(12703):  at android.os.HandlerThread.run(HandlerThread.java:61)
07-27 03:24:03.880 I/SurfaceView(12703): Returned canvas: null
07-27 03:24:03.880 D/AudioMTKStreamOut( 6231): AudioMTKStreamOut::write (-)
07-27 03:24:03.881 E/LocationManager(12703): RemoteException
07-27 03:24:03.881 E/LocationManager(12703): android.os.DeadObjectException
07-27 03:24:03.881 E/LocationManager(12703):    at android.os.BinderProxy.transact(Native Method)
07-27 03:24:03.881 E/LocationManager(12703):    at android.location.ILocationManager$Stub$Proxy.setTestProviderLocation(ILocationManager.java:980)
07-27 03:24:03.881 E/LocationManager(12703):    at android.location.LocationManager.setTestProviderLocation(LocationManager.java:1260)
07-27 03:24:03.881 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider.postLocation(MockProvider.java:90)
07-27 03:24:03.881 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider.postLocation(MockProvider.java:86)
07-27 03:24:03.881 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider$1.onChanged(MockProvider.java:30)
07-27 03:24:03.881 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder.notifyDataObserver(LocationHolder.java:90)
07-27 03:24:03.881 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder.access$000(LocationHolder.java:22)
07-27 03:24:03.881 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder$1.run(LocationHolder.java:53)
07-27 03:24:03.881 E/LocationManager(12703):    at android.os.Handler.handleCallback(Handler.java:808)
07-27 03:24:03.881 E/LocationManager(12703):    at android.os.Handler.dispatchMessage(Handler.java:103)
07-27 03:24:03.881 E/LocationManager(12703):    at android.os.Looper.loop(Looper.java:193)
07-27 03:24:03.881 E/LocationManager(12703):    at android.app.ActivityThread.main(ActivityThread.java:5292)
07-27 03:24:03.881 E/LocationManager(12703):    at java.lang.reflect.Method.invokeNative(Native Method)
07-27 03:24:03.881 E/LocationManager(12703):    at java.lang.reflect.Method.invoke(Method.java:515)
07-27 03:24:03.881 E/LocationManager(12703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
07-27 03:24:03.881 E/LocationManager(12703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
07-27 03:24:03.881 E/LocationManager(12703):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-27 03:24:03.881 E/LocationManager(12703):    at dalvik.system.NativeStart.main(Native Method)
07-27 03:24:03.881 V/LocationHolder(12703): posting data:lat/lng: (51.89266548970252,-8.488979603910648)
07-27 03:24:03.883 E/LocationManager(12703): RemoteException
07-27 03:24:03.883 E/LocationManager(12703): android.os.DeadObjectException
07-27 03:24:03.883 E/LocationManager(12703):    at android.os.BinderProxy.transact(Native Method)
07-27 03:24:03.883 E/LocationManager(12703):    at android.location.ILocationManager$Stub$Proxy.setTestProviderLocation(ILocationManager.java:980)
07-27 03:24:03.883 E/LocationManager(12703):    at android.location.LocationManager.setTestProviderLocation(LocationManager.java:1260)
07-27 03:24:03.883 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider.postLocation(MockProvider.java:90)
07-27 03:24:03.883 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider.postLocation(MockProvider.java:86)
07-27 03:24:03.883 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.MockProvider$1.onChanged(MockProvider.java:30)
07-27 03:24:03.883 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder.notifyDataObserver(LocationHolder.java:90)
07-27 03:24:03.883 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder.access$000(LocationHolder.java:22)
07-27 03:24:03.883 E/LocationManager(12703):    at com.github.jinsen47.pokefaker.app.LocationHolder$1.run(LocationHolder.java:53)
07-27 03:24:03.883 E/LocationManager(12703):    at android.os.Handler.handleCallback(Handler.java:808)
07-27 03:24:03.883 E/LocationManager(12703):    at android.os.Handler.dispatchMessage(Handler.java:103)
07-27 03:24:03.883 E/LocationManager(12703):    at android.os.Looper.loop(Looper.java:193)
07-27 03:24:03.883 E/LocationManager(12703):    at android.app.ActivityThread.main(ActivityThread.java:5292)
07-27 03:24:03.883 E/LocationManager(12703):    at java.lang.reflect.Method.invokeNative(Native Method)
07-27 03:24:03.883 E/LocationManager(12703):    at java.lang.reflect.Method.invoke(Method.java:515)
07-27 03:24:03.883 E/LocationManager(12703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
07-27 03:24:03.883 E/LocationManager(12703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
07-27 03:24:03.883 E/LocationManager(12703):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-27 03:24:03.883 E/LocationManager(12703):    at dalvik.system.NativeStart.main(Native Method)
07-27 03:24:03.884 D/AEE/AED (18221): put_in_archive: Archive file /data/aee_exp/temp/db.WjJWQl/SYS_ANDROID_EVENT_LOG, size 3271

**Comment by jinsen47** [comment]
OK, something wrong about the joystick, it costs too much memory. I will fix it in next version. The first version cost less memory, but hard to control, you guys may have a try.

**Comment by jinsen47** [comment]
Fixed, if it happens again, reopen this issue.
