### ISSUE TITLE
Joypad disappear

### ISSUE THREAD

**Issue by hianghao** [jinsen47/PokeFaker#16]
Hi, the joypad will disappear randomly and reappear randomly in game. After a few occurence, it just won't reappear and I would need to restart the game.

**Comment by jinsen47** [comment]
Cant help, System kill apps when low memory left.

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by hianghao** [comment]
Sorry. Do you mean that its because of low memory in my phone? As in low RAM available? But I've locked the app in task manager.

**Comment by jinsen47** [comment]
Yes, it happened on my phone sometimes.
When severe low memory left, system killed almost every app in the background, lock or not doesn’t help.

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by hianghao** [comment]
I see... I guess its time to upgrade phone. Thanks for the reply and great app.

**Comment by jinsen47** [comment]
Pokemon Go itself keeps leaking memory, maybe they will improve this in the future.
And I will keep refactor my code to cost less system resources.
Enjoy it~
