### ISSUE TITLE
建议 可以不需要悬浮窗权限

### ISSUE THREAD

**Issue by Cornflower1991** [jinsen47/PokeFaker#18]
设置type为  WindowManager.LayoutParams.TYPE_TOAST ，可以不需要悬浮窗权限。 那后我发现有点卡，不知道是不是service 的那个handler 。

**Comment by jinsen47** [comment]
第一个是不是钻了某一个漏洞我记得? 在>21依然有效吗?
第二条我觉得你说得有可能, 有些朋友反应有性能问题, 不过我目前在开发新功能, 如果你有时间的话欢迎帮我提交一个PR

**Comment by Cornflower1991** [comment]
第一个 貌似在某些手机上是还是有问题，大部分好像没事 我这个手机5.1的是可以的。然后第二点我是一直显示的摇杆的，发现效果会好点。但是还是不很理想  摇杆 如果一直滑动到一个方向，等一会儿回调就不走了。我技术也一般。 也没有什么修改什么 。大概就简单修改了。 然后那个更改经纬度的感觉可不可以直接用provider，我反编译被人的好像都是直接操作的。或者是开子线程定时读取sp里的值  我也没试过。不知道靠谱不

**Comment by Cornflower1991** [comment]
对了 第一点在小米手机是 都不行的

**Comment by jinsen47** [comment]
第一点这个感觉可以不用修改, 毕竟使用这个软件的用户都应该知道要给权限.不知道给权限的用户并不是目标用户.
第二点这个,我这两天时间比较紧张,从DDMS的数据来看, 摇杆产生了大量一次性对象, 对GC造成负担比较大, 我周末去修复一下.
另外, 你提到的经纬度的问题, 我也都试过, 但是没有成功, 相关的代码应该在repo中, (HookLocationFaker), 不知道为什么, 也希望你能帮我找找原因.

**Comment by Cornflower1991** [comment]
我看网上说 反射调用下Location 的makeComplete  方法 然后第一点是因为 小米，魅族手机 默认是关闭的。 然后启动就看不到效果 然后加了这个 魅族是可以看到 ，小米还是不行。  
 Method localMethod = Location.class.getMethod("makeComplete", new Class[0]);
            if (localMethod != null)
                localMethod.invoke(localLocation, new Object[0]);
            localLocationManager.setTestProviderLocation(this.mProvider, localLocation);

**Comment by jinsen47** [comment]
makeComplete不过是补充了一些其他的字段，如果builder构建出来的字段足够的话，是不需要调用的。

**Comment by Cornflower1991** [comment]
噢 谢谢了。  然后更新模拟位置  貌似 需要在类似while（true） 这个的循环里 一直更新 才有用？ ，直接调用 好像不管用？
