### ISSUE TITLE
Floating pad disappeard in on pokemon v 0.31.0

### ISSUE THREAD

**Issue by zevozki** [jinsen47/PokeFaker#22]
Im using android 5.0.2, the module worked perfectly until the game force to update. After update the pad is working until loading screen appearsthen it vanish. When the game run to play the pre fixed location is still working but the pad is not because its disappeared.

**Comment by zevozki** [comment]
Update.  After disabled and enable the module and reboot it worked as usual. Best app so far among all

**Comment by jinsen47** [comment]
I'm considering replacing the joystick view in 2.0+. It's good, but I can do better.
