### ISSUE TITLE
Bypass gps

### ISSUE THREAD

**Issue by What-Zit-Tooya** [jinsen47/PokeFaker#3]
Is it possible to bypass gps? so pokemon go will assume gps on, but actually gps turned off.

**Comment by jinsen47** [comment]
Currently this app don’t use the real GPS to provide locations, but Pokemon Go would check if GPS is on.
If I would do this legal, it is not possible to accomplish.

P.S. The real GPS is NOT working, and it will not drain your battery. Please don’t worry.

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by What-Zit-Tooya** [comment]
Oh..ok, btw do you know what is indication if we get banned? some error message or other?

**Comment by jinsen47** [comment]
Em, your phone provide several kind of messages to locate its location.
1. Cell information
2. Wifi SSID detection
3. GPS signal

I just mock up this GPS signal(no satellites), if Pokemon Go collects other information, we will be exposed.

For now, i haven’t head anybody get banned, but it doesnt mean they won’t ban some in the future.

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by What-Zit-Tooya** [comment]
Ok, thank you.
Btw, i have an issue, sometimes i jumping back to original location, not in location that i've set before.

**Comment by jinsen47** [comment]
Never happened on me, maybe a bug.
May I ask what does ‘origin location’ mean? (0,0) in the center of atlantic? Or the first location selected on the map view?

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by What-Zit-Tooya** [comment]
Yes bro, in the center of atlantic. But it just sometimes.

**Comment by jinsen47** [comment]
I cannot reproduce that...
I opened and killed the App for about 50 times.
Perhaps it's a specific case on your phone.

**Comment by What-Zit-Tooya** [comment]
Hmm..probably yes. I check on xposed log but no error related to this module.
Btw, would you add feature continue walk / run? so we no need to always tap D-pad.

**Comment by jinsen47** [comment]
Joystick will be added vey soon, please wait for next version.

**Comment by What-Zit-Tooya** [comment]
So if we use joystick, can i run / walk without continue to touch screen?

**Comment by jinsen47** [comment]
When I say joystick, i mean a joystick view on the screen. 
You still have to touch the screen, but this time you may hold on the view instead of clicking it.

**Comment by What-Zit-Tooya** [comment]
Ohh..ok
But does it possible to add feature like press [run] or [walk] to continue walk / run? so no need to hold / touch frequently.

**Comment by jinsen47** [comment]
Joystick has a power parameter, the closer to center, the slower you moving.

I tried some max speed parameter, the speed I’ve chosen is almost the fastest speed to hatch eggs.

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by What-Zit-Tooya** [comment]
But i get using joystick is make pokemon go lag. There is delay between touch joystick and trainer moving.
Also add feature search location & input latitude & longitude if possible.

**Comment by jinsen47** [comment]
I have found the reason of delay, but sill cannot improve this, I'm still working on it.
Input and position view will be added soon.

**Comment by What-Zit-Tooya** [comment]
Nice.. (y)
