### ISSUE TITLE
开了模拟位置，pokemon go提示"Failed to detect location"

### ISSUE THREAD

**Issue by sonuan** [jinsen47/PokeFaker#5]
开了模拟位置，就提示"Failed to detect location".

**Comment by jinsen47** [comment]
可能是一个Bug， 请贴一下Xposed的log好吗？
在Xposed Installer的log模块里

Github: https://github.com/jinsen47 https://github.com/jinsen47/
jinsen47@gmail.com

**Comment by Jasonrw** [comment]
之前也是这样 后来发现是没重启 xposed装完模块要重启。第一次用，见谅

**Comment by jinsen47** [comment]
没关系，我已经更新了README~
