### ISSUE TITLE
需要打开模拟位置

### ISSUE THREAD

**Issue by xujianbiao** [jinsen47/PokeFaker#6]
需要打开模拟位置的话，最好配合一下其他模块，防止检测到启用了“允许位置伪装”，不然pg检测到打开了模拟位置，会一直提示Failed to detect location

**Comment by jinsen47** [comment]
我参考了著名的MockMockLocation，并改进了他的代码，只用我的插件可以完全不用其他的库。
如果有Fail to detect location报出来的话，请报Bug。

**Comment by xujianbiao** [comment]
原来你这个模块已经包含了MockMockLocation的功能了。。厉害厉害，待我测试一下
