### ISSUE TITLE
Android6.0提示Failed to detect location

### ISSUE THREAD

**Issue by fatsoon** [jinsen47/PokeFaker#7]
模拟位置用用选择了PokeFaker，进游戏提示Failed to detect location，另一台手机Android5.1.1却没这个问题

**Comment by xujianbiao** [comment]
打开之后地图一片蓝是怎么回事？啥都没出来。。

**Comment by jinsen47** [comment]
@fatsoon Xposed管理器中启用了模块是不应该有这个问题的。。。

**Comment by jinsen47** [comment]
@xujianbiao 打开地图默认在（0，0）你可以缩小一点回到陆地上

**Comment by haseoxth** [comment]
模块很实用，感谢作者的付出（看了下现在同类的模块在仓库内已有5款，作者所出的版本是第一个让我可以正常使用的）。
关于上面几位提到的相关问题我个人在使用当中也有遇到过，在这里写下一些个人的解决方案：
本人的运行环境为原生安卓6.0.1
1.首先需要在安装过后检查下是否已经给过程序"位置信息"权限，我个人的情况是在安装过后进入程序时没有弹出请求权限的窗口（而这点可能导致进入程序时谷歌地图无法显示世界地图）。

2.之后在开发者选项的"选择模拟位置信息应用"里选中PokeFaker，该处不选中程序的话在安卓6.0上运行时会出现程序闪退的问题。因为目前的版本内还没有添加相关的提示信息所以应该有人会感到困惑。

3.最后是关于Failed to detect location的错误提示，我去国外论坛看了下，关于这点国外网友的解决方案是关闭手机内的模拟位置选项，但结合我们安装此应用的目的考虑自然是不会如此去做的，因而我个人认为这可能是由于在模拟位置信息时触发了程序内的某些检测机制所导致的（奇怪的是并非所有人在使用时都会遇到这个错误项，因而以上也都只是个人的揣测罢了），为了规避此错误选择额外安装了Mock Mock Locations模块，在个人的机器上问题得以解决。

**Comment by fatsoon** [comment]
感谢@haseoxth 我也是原生6.0.1，安装Mock Mock Locations模块后可以正常使用了

**Comment by xujianbiao** [comment]
作者之前说了此模块集成了Mock Mock Locations的代码，但不知道为什么不起作用

**Comment by jinsen47** [comment]
我去验证一下这个问题，不过我确实解决了MockMockLocation在6.0以下对PokemonGO无效的问题，不知道为什么6.0反而出了问题。

**Comment by xujianbiao** [comment]
@jinsen47 我用Mock Mock Location试过，还是会有这个提示，改用Hide Mock Location一切正常，miui8系统

**Comment by jinsen47** [comment]
已经修正, 6.0/5.1/5.0 都测试通过,可用,不再需要其他模块
